name: 🧹 Chore
description: 문서, 설정, 패키지 업데이트 등 유지보수 작업
title: "[chore] 작업 제목"
labels: ["chore"]
body:
  - type: textarea
    id: what
    attributes:
      label: 📦 작업 내용
      description: 어떤 작업을 수행할 예정인가요?
      placeholder: ex) ESLint 설정 수정, README 업데이트 등
    validations:
      required: true
