name: 📚 Docs
description: 문서 수정, README, 주석, 위키 등 작업
title: "[docs] 문서 제목"
labels: ["docs"]
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 문서 설명
      description: 어떤 문서를 수정/추가/삭제하나요?
      placeholder: ex) API 명세 문서 업데이트
    validations:
      required: true
