name: 🧪 Test
description: 테스트 코드 추가 또는 테스트 환경 구성
title: "[test] 테스트 작업 제목"
labels: ["test"]
body:
  - type: textarea
    id: what
    attributes:
      label: 🧪 테스트 대상
      description: 어떤 기능/로직에 대한 테스트인가요?
      placeholder: ex) 여행 추천 API 단위 테스트
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 🔍 테스트 항목
      description: 테스트에서 다루는 주요 항목을 정리해주세요
      placeholder: |
        - 정상 응답 반환
        - 예외 케이스 처리
